# Generated by Django 2.2.19 on 2022-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20221208_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ident',
            field=models.TextField(default='1', max_length=50),
        ),
    ]
