# Generated by Django 2.2.19 on 2022-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20221208_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='<без заголовка>', max_length=14, verbose_name='Заголовок'),
        ),
    ]
