# Generated by Django 2.2.19 on 2022-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20221210_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=42, verbose_name='Заголовокы'),
        ),
    ]
